import { MigrationInterface, QueryRunner } from 'typeorm';

export class CanonicalCategoryAndMenu1791421925807 implements MigrationInterface {
  name = 'CanonicalCategoryAndMenu1791421925807';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await this.requireEmptyTables(queryRunner);
    await queryRunner.query(`
            ALTER TABLE "menu_items" DROP COLUMN "created_at"
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items" DROP COLUMN "updated_at"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories" DROP COLUMN "created_at"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories" DROP COLUMN "updated_at"
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items"
            ADD "category_id" integer NOT NULL
        `);
    await queryRunner.query(`
            CREATE TYPE "public"."menu_item_state" AS ENUM('ACTIVE', 'INACTIVE')
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items"
            ADD "state" "public"."menu_item_state" NOT NULL DEFAULT 'ACTIVE'
        `);
    await queryRunner.query(`
            CREATE TYPE "public"."menu_item_availability" AS ENUM('AVAILABLE', 'UNAVAILABLE')
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items"
            ADD "availability" "public"."menu_item_availability" NOT NULL DEFAULT 'AVAILABLE'
        `);
    await queryRunner.query(`
            ALTER TABLE "categories" DROP CONSTRAINT "PK_8ac255b9743120147e61fb5465b"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories" DROP COLUMN "id_category"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories"
            ADD "id_category" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL
        `);
    await queryRunner.query(`
            ALTER TABLE "categories"
            ADD CONSTRAINT "PK_8ac255b9743120147e61fb5465b" PRIMARY KEY ("id_category")
        `);
    await queryRunner.query(`
            ALTER TABLE "categories"
            ADD CONSTRAINT "UQ_3633cd9f1a9da406847d64d02b5" UNIQUE ("name_category")
        `);
    await queryRunner.query(`
            CREATE INDEX "IDX_menu_items_category_id" ON "menu_items" ("category_id")
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items"
            ADD CONSTRAINT "fk_menu_items_categories" FOREIGN KEY ("category_id") REFERENCES "categories"("id_category") ON DELETE RESTRICT ON UPDATE NO ACTION
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await this.requireEmptyTables(queryRunner);
    await queryRunner.query(`
            ALTER TABLE "menu_items" DROP CONSTRAINT "fk_menu_items_categories"
        `);
    await queryRunner.query(`
            DROP INDEX "public"."IDX_menu_items_category_id"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories" DROP CONSTRAINT "UQ_3633cd9f1a9da406847d64d02b5"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories" DROP CONSTRAINT "PK_8ac255b9743120147e61fb5465b"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories" DROP COLUMN "id_category"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories"
            ADD "id_category" uuid NOT NULL DEFAULT uuid_generate_v4()
        `);
    await queryRunner.query(`
            ALTER TABLE "categories"
            ADD CONSTRAINT "PK_8ac255b9743120147e61fb5465b" PRIMARY KEY ("id_category")
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items" DROP COLUMN "availability"
        `);
    await queryRunner.query(`
            DROP TYPE "public"."menu_item_availability"
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items" DROP COLUMN "state"
        `);
    await queryRunner.query(`
            DROP TYPE "public"."menu_item_state"
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items" DROP COLUMN "category_id"
        `);
    await queryRunner.query(`
            ALTER TABLE "categories"
            ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()
        `);
    await queryRunner.query(`
            ALTER TABLE "categories"
            ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items"
            ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()
        `);
    await queryRunner.query(`
            ALTER TABLE "menu_items"
            ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()
        `);
  }

  private async requireEmptyTables(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `LOCK TABLE "categories", "menu_items" IN ACCESS EXCLUSIVE MODE`,
    );
    const rows: { has_data: boolean }[] = await queryRunner.query(`
            SELECT EXISTS (SELECT 1 FROM "categories")
                OR EXISTS (SELECT 1 FROM "menu_items") AS has_data
        `);
    if (rows[0].has_data) {
      throw new Error(
        'La migración canónica requiere categories y menu_items vacías: cambia IDs UUID a enteros y elimina columnas antiguas. Se detuvo para conservar los datos. Si hay registros existentes, prepara primero una migración de datos.',
      );
    }
  }
}
